Bump version to 4.2, check SRC and PKG dirs, use CMake, build txz

diff --git a/kchmviewer.SlackBuild b/kchmviewer.SlackBuild
--- a/kchmviewer.SlackBuild
+++ b/kchmviewer.SlackBuild
@@ -2,62 +2,79 @@
 #
 # SlackBuild for KchmViewer
 # Written by Georgi D. Sotirov <gdsotirov@dir.bg>
+# Visit SlackBuild at http://sotirov-bg.net/slackpack/
 #
 
 . ../slack-package.conf
 
 NAME=kchmviewer
-VERSION=3.1
-RELEASE=2
-BUILD=1
-
+VERSION=4.2
+BUILD=${BUILD:-1}
 ARCH=${ARCH:-i486}
+
+CWD=${CWD:-`pwd`}
 TMP=${TMP:-/tmp}
 
-cd $TMP
-tar -zxvf $CWD/$NAME-$VERSION-$RELEASE.tar.gz
+if [ ! -e $TMP ]; then
+  mkdir -p $TMP # location to build the source
+fi
+
 SRC=$TMP/$NAME-$VERSION
+if [ -e $SRC -a -d $SRC ]; then
+  echo "Source directory '$SRC' already exists! Plaese, move it or remove it."
+  exit 1
+fi
+
+PKG=$TMP/package-$NAME
+if [ -e $PKG -a -d $PKG ]; then
+  echo "Package creation directory '$PKG' already exists! Please, move it or remove it."
+  exit 2
+fi
+mkdir -p $PKG
+
+# Extract the sources
+cd $TMP
+tar -xvf $CWD/$NAME-$VERSION.tar.gz || exit 1
 cd $SRC
 fix_source
 
-CFLAGS=$SLKCFLAGS \
-CXXFLAGS=$SLKCFLAGS \
-./configure --build=$ARCH-slackware-linux \
-            --host=$ARCH-slackware-linux \
-            --prefix=/usr \
-            --enable-shared=yes \
-            --enable-static=no \
-            --with-kde \
-            --disable-debug
+# Configure
+cmake -DCMAKE_BUILD_TYPE=None \
+      -DCMAKE_C_FLAGS:STRING="$SLKCFLAGS -DNDEBUG" \
+      -DCMAKE_CXX_FLAGS:STRING="$SLKCFLAGS -DNDEBUG -DQT_NO_DEBUG" \
+      -DLIB_SUFFIX=${LIBDIRSUFFIX} \
+      -DCMAKE_INSTALL_PREFIX=/usr \
+      -DCMAKE_VERBOSE_MAKEFILE=1 || exit 2
 
-make || exit 1
-
-PKG="$TMP/package-$NAME"
-mkdir -p $PKG
-
-make DESTDIR=$PKG install
+# Build & install
+make -j4 || exit 3
+make DESTDIR=$PKG install || exit 4
 
 bin_perms $PKG
 ( cd $PKG; strip_bin; strip_lib )
-DOCFILES="$DOCFILES DCOP-bingings" # There must be an error in the filename
+DOCFILES="$DOCFILES DBUS-bindings"
 ( cd $SRC; create_docs $PKG $NAME-$VERSION )
 
-mkdir -p $PKG/install
-install -m 644 $CWD/slack-desc     $PKG/install
-install -m 644 $CWD/slack-required $PKG/install
+# Prepare
+install -m 755 -d $PKG/install
+install -m 644 $CWD/slack-desc     $PKG/install/slack-desc
+install -m 644 $CWD/slack-required $PKG/install/slack-required
 
-mkdir -p $PKG/usr/src/slackbuilds/$NAME-$VERSION
-install -m 644 $CWD/slack-desc       $PKG/usr/src/slackbuilds/$NAME-$VERSION
-install -m 644 $CWD/slack-required   $PKG/usr/src/slackbuilds/$NAME-$VERSION
-install -m 644 $CWD/$NAME.SlackBuild $PKG/usr/src/slackbuilds/$NAME-$VERSION
+SBDIR=$PKG/usr/src/slackbuilds/$NAME-$VERSION
+install -m 755 -d $SBDIR
+install -m 644 $CWD/slack-desc       $SBDIR/slack-desc
+install -m 644 $CWD/slack-required   $SBDIR/slack-required
+install -m 644 $CWD/$NAME.SlackBuild $SBDIR/$NAME.SlackBuild
 
+# Assemble
 cd $PKG
 PKGNAME=$NAME-$VERSION-$ARCH-$BUILD$MYIN
-makepkg -l y -c n $PKG_DIR/$PKGNAME.tgz
+makepkg -l y -c n $PKG_DIR/$PKGNAME.txz
 cd $PKG_DIR
-md5sum $PKGNAME.tgz > $PKGNAME.tgz.md5
+md5sum $PKGNAME.txz > $PKGNAME.txz.md5
 cat $PKG/install/slack-desc > $PKG_DIR/$PKGNAME.txt
 
+# Cleanup (optionally)
 if [ "$1" == "--cleanup" ]; then
   rm -r $SRC
   rm -r $PKG
